### ISSUE TITLE
EnableButtons don't show state bitmaps under (some) GTK implementations

### ISSUE THREAD

**Issue by mickp** [microscope-cockpit/cockpit#475]
This class does not work on default gnome shell. This is because bitmaps in buttons are ignored if there's a text label. We will need a separate class that has a toggle button next to the bitmap.

_Originally posted by @carandraug in https://github.com/MicronOxford/cockpit/pull/447#discussion_r251444251

**Comment by carandraug** [comment]
I'm not sure when but this seems to have been fixed in upstream (at least on the default Gnome theme).

The state bitmaps (green/red/orange square) on the camera/lights/etc buttons are now displayed on GTK. The positioning of the bitmap is not honored though (we request the bitmap to be placed at the right end of the button but it is being placed right as if it was another character of the text (centered). Anyway, not Something we can fix, so closing.
