### ISSUE TITLE
Its possible to loose the main window.

### ISSUE THREAD

**Issue by iandobbie** [microscope-cockpit/cockpit#677]
The new window menu will surface and any window you select and I beleive move from out to view to in view, however there is no entry for the main window. 

I ran cockpit on a 2 monitor setup, with the main window on the second monitor. stopped cockpit, saving window positions. removed the second monitor and restart, the main window is now off the viewable area and doesn't seem to be recoverable. This is on a macbook.

**Comment by carandraug** [comment]
> however there is no entry for the main window.

I guess this is only needed on a Mac, where the menu bar is on the top of the display. On other platforms, the menu bar is on top of the window, so if the window is not visible the menu bar is also not accessible.

> I ran cockpit on a 2 monitor setup, with the main window on the second monitor. stopped cockpit, saving window positions. removed the second monitor and restart, the main window is now off the viewable area and doesn't seem to be recoverable. This is on a macbook.

The positioning of windows on previously saved positions is done with `wx.Window.SetPosition` on `cockpit.CockpitApp.SetWindowPositions`.  I can't reproduce the issue on GTK3 (using an invalid position with `wx.Window.SetPosition` moves the window to the closest valid position) so can someone with a Mac try to fix this?  I think we need some sort of check on `CockpitApp.SetWindowPositions`.

We already have a check on `cockpit.gui.mainWindow.WindowsMenu.OnWindowTitle` but that only checks for the validity of the display index. But what happens if the display index is "correct" but the display changed size? i.e., if you only have the large display enabled with the main window on a corner, exit cockpit saving coordinates, then disable the large display and enable the builtin smaller-display of the laptop so that the main window is on the right display index (there is only one), but still outside the monitor, what happens?

Also, is this a Mac only problem? What happens on Windows?

Also also, before the new window menu, that menu was accessible by right click on the main window background. What did you do back then?

**Comment by iandobbie** [comment]
New "feature" if you have the new tabbed single window view that Ilan showed it is possible to loose everything. We ned some menu item or similar to allow windows to be rescued if totally lost from the desktop.

**Comment by iandobbie** [comment]
Can we just add the main window to the windows menu on darwin?

**Comment by juliomateoslangerak** [comment]
In principle, the owner of anything I write during my working ours is the CNRS. But I ignore all the details.

**Comment by iandobbie** [comment]
Either is was fixed by the OS or other code. It is no longer a problem on my system macOS 12.6.7 so closing.
